//常量定義
var FONT_DEFAULT_NAME = "Marker Felt";
var FONT_DEFAULT_SIZE = 30;
var FONT_DEFAULT_MIN = 10;

var FONT_DEFAULT_SMALL = 14;
var FONT_DEFAULT_SMALL2 = 16;
var FONT_DEFAULT_SMALL3 = 18;

var FONT_DEFAULT_MIDDLE = 24;


//定義 角色面朝 方向
var ROLE_FACE_BOTTOM		=	0;
var ROLE_FACE_LEFT			=	1;
var ROLE_FACE_TOP			=	2;
var ROLE_FACE_RIGHT			=	3;

var ROLE_FACE_ANIMATION		=	0.25;


//定義 角色 唯一ID
var ROLE_ID_MAIN		=	1;
var ROLE_ID_YAN13		=	2;
var ROLE_NAME_YAN13		=	"ROLE_NAME_YAN13";
var ROLE_ID_CAOBIN		=	3;
var ROLE_NAME_CAOBIN	=	"ROLE_NAME_CAOBIN";

var	ROLE_ID_XIE3		=	4;
var ROLE_NAME_XIE3		=	"ROLE_NAME_XIE3";


//定義 敵人 ID
var ROLE_ID_9000		=	1000;
var ROLE_NAME_9000		=	"ROLE_NAME_9000";
var ROLE_ID_LICAOQING		=	1001;
var ROLE_NAME_LICAOQING		=	"ROLE_NAME_LICAOQING";


//定義 普通 單位
var ROLE_ID_INFANTRY		=	2000;	//步兵
var ROLE_NAME_INFANTRY		=	"ROLE_NAME_INFANTRY";

var ROLE_ID_ARCHER			=	2500;		//弓箭手
var ROLE_NAME_ARCHER		=	"ROLE_NAME_ARCHER";


var ROLE_ID_COUNSELOR		=	3000;
var ROLE_NAME_COUNSELOR		=	"ROLE_NAME_COUNSELOR";