//常量定義
var FONT_DEFAULT_NAME = "Marker Felt";
var FONT_DEFAULT_SIZE = 30;
var FONT_DEFAULT_MIN = 10;
var FONT_DEFAULT_SMALL = 14;
var FONT_DEFAULT_MIDDLE = 24;

//定義 角色 唯一ID
var ROLE_ID_MAIN		=	1;
var ROLE_ID_YAN13		=	2;
var ROLE_NAME_YAN13		=	"ROLE_NAME_YAN13";
var ROLE_ID_CAOBIN		=	3;
var ROLE_NAME_CAOBIN	=	"ROLE_NAME_CAOBIN";

